# Generated by Django 4.2.7 on 2023-12-02 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('notes', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowing_date', models.DateField(auto_now=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='borrowed', max_length=255)),
                ('notes', models.CharField(default='', max_length=255)),
                ('borrower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='objects.userprofile')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='objects.object')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lent_set', to='objects.userprofile')),
            ],
        ),
    ]
