# Generated by Django 4.2.7 on 2023-12-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='borrowing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
