# Generated by Django 4.2.7 on 2023-12-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_alter_borrow_borrowing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='object',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
