# Generated by Django 4.2.7 on 2023-12-06 11:28

from django.db import migrations, models
import django.db.models.deletion


def move_owner_to_object(apps, schema_editor):
    Borrow = apps.get_model("objects", "Borrow")
    borrows = Borrow.objects.all()
    for borrow in borrows:
        borrow.object.owner_id = borrow.owner_id
        borrow.object.save()


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_alter_borrow_notes_alter_object_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lent_set', to='objects.userprofile'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lent_set_old', to='objects.userprofile'),
        ),
        migrations.RunPython(move_owner_to_object, migrations.RunPython.noop),
    ]
