# Generated by Django 4.2.7 on 2023-12-06 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_object_owner_alter_borrow_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='owner',
        ),
        migrations.AlterField(
            model_name='object',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lent_set', to='objects.userprofile'),
        ),
    ]
